"use client";
import Link from "next/link";
import { useState } from "react";
import type { FormEvent } from "react";
type FormState = { firstName: string; lastName: string; email: string; phoneNumber: string; password: string; confirmPassword: string; terms: boolean; privacy: boolean };
type FieldErrors = Partial<Record<keyof FormState, string>>;
const initialState: FormState = { firstName: "", lastName: "", email: "", phoneNumber: "", password: "", confirmPassword: "", terms: false, privacy: false };
function normalizePhone(value: string): string { const compact = value.replace(/[\s().-]/g, ""); return compact.startsWith("00") ? `+${compact.slice(2)}` : compact; }
export default function PatientSignupForm() {
  const [form, setForm] = useState<FormState>(initialState); const [state, setState] = useState<"idle" | "submitting" | "verification" | "error" | "verified">("idle"); const [message, setMessage] = useState("Your account credentials and verification are handled securely by Cognito."); const [showPassword, setShowPassword] = useState(false); const [fieldErrors, setFieldErrors] = useState<FieldErrors>({}); const [verificationEmail, setVerificationEmail] = useState(""); const [verificationCode, setVerificationCode] = useState(""); const [verificationBusy, setVerificationBusy] = useState(false);
  function update(field: keyof FormState, value: string | boolean) { setForm((current) => ({ ...current, [field]: value })); setFieldErrors((current) => ({ ...current, [field]: undefined })); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const phoneNumber = normalizePhone(form.phoneNumber);
    const errors: FieldErrors = {}; if (!form.firstName.trim()) errors.firstName = "First Name is required."; if (!form.lastName.trim()) errors.lastName = "Last Name is required."; if (!form.email.trim()) errors.email = "Email Address is required."; else if (!/^\S+@\S+\.\S+$/.test(form.email.trim())) errors.email = "Enter a valid email address."; if (!/^\+[1-9]\d{7,14}$/.test(phoneNumber)) errors.phoneNumber = "Use international format, such as +18765551234."; if (!form.password) errors.password = "Password is required."; if (form.password !== form.confirmPassword) errors.confirmPassword = "Passwords do not match."; if (!form.terms) errors.terms = "Accept the Terms of Use."; if (!form.privacy) errors.privacy = "Acknowledge the Privacy Policy.";
    if (Object.keys(errors).length) { setFieldErrors(errors); setState("error"); setMessage("Please correct the highlighted account fields."); return; }
    setState("submitting"); setMessage("Creating your secure account…");
    try {
      const response = await fetch("/api/v1/auth/signup", { method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ firstName: form.firstName.trim(), lastName: form.lastName.trim(), email: form.email.trim(), phoneNumber, password: form.password }) });
      setForm((current) => ({ ...current, password: "", confirmPassword: "" }));
      const payload = await response.json().catch(() => ({})) as { data?: { verificationRequired?: boolean }; error?: { message?: string } };
      if (!response.ok || !payload.data) { setState("error"); setMessage(payload.error?.message ?? "We couldn't create the account right now. Please try again."); return; }
      if (payload.data.verificationRequired) { setVerificationEmail(form.email.trim()); setState("verification"); setMessage("A verification code was sent to your email. Enter it below to activate your account."); } else { setState("verified"); setMessage("Your account is ready. Continue to sign in securely."); }
    } catch { setState("error"); setMessage("We couldn't reach secure account creation. Please try again."); }
  }
  async function confirm() { setVerificationBusy(true); setMessage("Verifying your account securely…"); try { const response = await fetch("/api/v1/auth/signup/confirm", { method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ email: verificationEmail, code: verificationCode }) }); const payload = await response.json().catch(() => ({})) as { data?: { verified?: boolean }; error?: { message?: string } }; if (!response.ok || !payload.data?.verified) { setState("verification"); setMessage(payload.error?.message ?? "We couldn't verify the account right now. Check the code and try again."); return; } setState("verified"); setMessage("Your email is verified. You can now sign in securely."); } catch { setState("verification"); setMessage("We couldn't reach account verification. Please try again."); } finally { setVerificationBusy(false); } }
  async function resend() { setVerificationBusy(true); setMessage("Sending a new verification code…"); try { const response = await fetch("/api/v1/auth/signup/resend", { method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ email: verificationEmail }) }); setMessage(response.ok ? "A new verification code was sent. Check your email." : "We couldn't send a new code right now. Please wait and try again."); } catch { setMessage("We couldn't send a new code right now. Please wait and try again."); } finally { setVerificationBusy(false); } }
  if (state === "verification") return <div className="signup-verification" aria-live="polite"><span className="auth-step-number">✉</span><p className="detail-kicker">Verify your account</p><h2>Enter your verification code</h2><p>{message}</p><label className="verification-code-label">Verification code<input inputMode="numeric" autoComplete="one-time-code" value={verificationCode} onChange={(event) => setVerificationCode(event.target.value.replace(/\D/g, "").slice(0, 8))} aria-describedby="verification-status" /></label><p id="verification-status" className="auth-notice" role="status">Cognito sent the code to the email address you provided.</p><button type="button" className="detail-primary" onClick={confirm} disabled={verificationBusy || verificationCode.length < 4}>{verificationBusy ? "Verifying…" : "Verify account"}</button><button type="button" className="auth-text-button" onClick={resend} disabled={verificationBusy}>Resend code</button><Link href="/sign-in">Return to sign in</Link></div>;
  if (state === "verified") return <div className="signup-verification" aria-live="polite"><span className="auth-step-number">✓</span><p className="detail-kicker">Account verified</p><h2>You’re ready to sign in</h2><p>{message}</p><Link className="detail-primary" href="/sign-in">Continue to sign in</Link><small>Cognito handles your credentials and verification. Rejuvonix does not store your password.</small></div>;
  return <form className="signup-form" onSubmit={submit} noValidate aria-describedby="signup-status"><div className="signup-name-grid"><label>First Name<input name="firstName" value={form.firstName} onChange={(event) => update("firstName", event.target.value)} autoComplete="given-name" required /></label><label>Last Name<input name="lastName" value={form.lastName} onChange={(event) => update("lastName", event.target.value)} autoComplete="family-name" required /></label></div><label>Email Address<input type="email" name="email" value={form.email} onChange={(event) => update("email", event.target.value)} autoComplete="email" required /></label><label>Mobile Phone Number<input type="tel" name="phoneNumber" value={form.phoneNumber} onChange={(event) => update("phoneNumber", event.target.value)} autoComplete="tel" placeholder="+1 876 555 1234" inputMode="tel" required /><small>Use international format, for example +18765551234.</small></label><label>Password<span className="signup-password-wrap"><input type={showPassword ? "text" : "password"} name="password" value={form.password} onChange={(event) => update("password", event.target.value)} autoComplete="new-password" required /><button type="button" className="signup-password-toggle" onClick={() => setShowPassword((current) => !current)} aria-pressed={showPassword}>{showPassword ? "Hide" : "Show"}</button></span><small>Cognito validates this password against the configured account policy.</small></label><label>Confirm Password<input type={showPassword ? "text" : "password"} name="confirmPassword" value={form.confirmPassword} onChange={(event) => update("confirmPassword", event.target.value)} autoComplete="new-password" required /></label><fieldset className="signup-consents"><legend>Before you continue</legend><label><input type="checkbox" checked={form.terms} onChange={(event) => update("terms", event.target.checked)} required /><span>I agree to the <Link href="/terms">Terms of Use</Link>.</span></label><label><input type="checkbox" checked={form.privacy} onChange={(event) => update("privacy", event.target.checked)} required /><span>I acknowledge the <Link href="/privacy">Privacy Policy</Link>.</span></label></fieldset>{Object.keys(fieldErrors).length > 0 && <ul className="signup-field-errors" aria-label="Fields to correct">{Object.entries(fieldErrors).map(([field, error]) => error && <li key={field}>{error}</li>)}</ul>}<p id="signup-status" className={`auth-notice ${state === "error" ? "auth-notice-error" : ""}`} role={state === "error" ? "alert" : "status"}>{message}</p><button type="submit" className="detail-primary" disabled={state === "submitting"} aria-busy={state === "submitting"}>{state === "submitting" ? "Creating account…" : "Create Account"}</button><p className="signup-switch">Already have an account? <Link href="/sign-in">Sign in</Link></p></form>;
}
