"use client";
import Link from "next/link";
import { useState } from "react";
import type { FormEvent } from "react";
type FormState = { firstName: string; lastName: string; email: string; phoneNumber: string; password: string; confirmPassword: string; terms: boolean; privacy: boolean };
const initialState: FormState = { firstName: "", lastName: "", email: "", phoneNumber: "", password: "", confirmPassword: "", terms: false, privacy: false };
function normalizePhone(value: string): string { const compact = value.replace(/[\s().-]/g, ""); return compact.startsWith("00") ? `+${compact.slice(2)}` : compact; }
export default function PatientSignupForm() {
  const [form, setForm] = useState<FormState>(initialState); const [state, setState] = useState<"idle" | "submitting" | "verification" | "error">("idle"); const [message, setMessage] = useState("Your account credentials and verification are handled securely by Cognito."); const [showPassword, setShowPassword] = useState(false);
  function update(field: keyof FormState, value: string | boolean) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const phoneNumber = normalizePhone(form.phoneNumber);
    if (!form.firstName.trim() || !form.lastName.trim() || !/^\S+@\S+\.\S+$/.test(form.email.trim()) || !/^\+[1-9]\d{7,14}$/.test(phoneNumber)) { setState("error"); setMessage("Enter your name, a valid email address, and a phone number in international format, such as +18765551234."); return; }
    if (!form.password || form.password !== form.confirmPassword) { setState("error"); setMessage("Enter the same password in both password fields. Cognito will enforce the configured password requirements."); return; }
    if (!form.terms || !form.privacy) { setState("error"); setMessage("Please accept the Terms of Use and acknowledge the Privacy Policy to continue."); return; }
    setState("submitting"); setMessage("Creating your secure account…");
    try {
      const response = await fetch("/api/v1/auth/signup", { method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ firstName: form.firstName.trim(), lastName: form.lastName.trim(), email: form.email.trim(), phoneNumber, password: form.password }) });
      setForm((current) => ({ ...current, password: "", confirmPassword: "" }));
      const payload = await response.json().catch(() => ({})) as { data?: { verificationRequired?: boolean }; error?: { message?: string } };
      if (!response.ok || !payload.data) { setState("error"); setMessage(payload.error?.message ?? "We couldn't create the account right now. Please try again."); return; }
      setState("verification"); setMessage(payload.data.verificationRequired ? "Check your email for Cognito verification instructions, then return to sign in." : "Your account is ready. Continue to sign in securely.");
    } catch { setState("error"); setMessage("We couldn't reach secure account creation. Please try again."); }
  }
  if (state === "verification") return <div className="signup-verification" aria-live="polite"><span className="auth-step-number">✓</span><p className="detail-kicker">Account created securely</p><h2>Check your email</h2><p>{message}</p><Link className="detail-primary" href="/sign-in">Continue to sign in</Link><small>Cognito handles verification before normal account access. Rejuvonix does not store your password.</small></div>;
  return <form className="signup-form" onSubmit={submit} noValidate aria-describedby="signup-status"><div className="signup-name-grid"><label>First Name<input name="firstName" value={form.firstName} onChange={(event) => update("firstName", event.target.value)} autoComplete="given-name" required /></label><label>Last Name<input name="lastName" value={form.lastName} onChange={(event) => update("lastName", event.target.value)} autoComplete="family-name" required /></label></div><label>Email Address<input type="email" name="email" value={form.email} onChange={(event) => update("email", event.target.value)} autoComplete="email" required /></label><label>Mobile Phone Number<input type="tel" name="phoneNumber" value={form.phoneNumber} onChange={(event) => update("phoneNumber", event.target.value)} autoComplete="tel" placeholder="+1 876 555 1234" inputMode="tel" required /><small>Use international format, for example +18765551234.</small></label><label>Password<span className="signup-password-wrap"><input type={showPassword ? "text" : "password"} name="password" value={form.password} onChange={(event) => update("password", event.target.value)} autoComplete="new-password" required /><button type="button" className="signup-password-toggle" onClick={() => setShowPassword((current) => !current)} aria-pressed={showPassword}>{showPassword ? "Hide" : "Show"}</button></span><small>Cognito validates this password against the configured account policy.</small></label><label>Confirm Password<input type={showPassword ? "text" : "password"} name="confirmPassword" value={form.confirmPassword} onChange={(event) => update("confirmPassword", event.target.value)} autoComplete="new-password" required /></label><fieldset className="signup-consents"><legend>Before you continue</legend><label><input type="checkbox" checked={form.terms} onChange={(event) => update("terms", event.target.checked)} required /><span>I agree to the <Link href="/terms">Terms of Use</Link>.</span></label><label><input type="checkbox" checked={form.privacy} onChange={(event) => update("privacy", event.target.checked)} required /><span>I acknowledge the <Link href="/privacy">Privacy Policy</Link>.</span></label></fieldset><p id="signup-status" className={`auth-notice ${state === "error" ? "auth-notice-error" : ""}`} role={state === "error" ? "alert" : "status"}>{message}</p><button type="submit" className="detail-primary" disabled={state === "submitting"} aria-busy={state === "submitting"}>{state === "submitting" ? "Creating account…" : "Create Account"}</button><p className="signup-switch">Already have an account? <Link href="/sign-in">Sign in</Link></p></form>;
}
