import Link from "next/link";
import { Product, products } from "./product-data";
import { SiteFooter, SiteHeader } from "./SiteChrome";

export function ProductPage({product}: {product: Product}) {
  const related = products.filter(item => item.slug !== product.slug).slice(0,3);
  return <main className="detail-page">
    <SiteHeader />
    <section className="product-hero-detail">
      <div className="product-hero-copy"><p className="detail-kicker">{product.status}</p><h1>{product.name}</h1><p className="product-ingredient">with {product.ingredient}</p><ul>{product.highlights.map(item => <li key={item}>{item}</li>)}</ul><Link className="detail-primary" href="/get-started">Check eligibility</Link><Link className="safety-link" href="#important-safety">Important safety information</Link></div>
      <div className="product-hero-product"><div className="product-aura"></div><img src={product.image} alt={`${product.name} product packaging`} /><span>{product.cadence}</span></div>
    </section>
    <section className="product-meet"><div className="product-meet-image"><img src={product.heroImage} alt="A Rejuvonix member enjoying a healthy everyday routine" /></div><div className="product-meet-copy"><p className="detail-kicker">Meet {product.shortName}</p><h2>Prescription care designed to fit real life.</h2><p>{product.intro}</p><div className="product-info-columns"><div><h3>About the treatment</h3>{product.ingredientPoints.map(item => <p key={item}>✓ {item}</p>)}</div><div><h3>How to take it</h3>{product.directions.map(item => <p key={item}>✓ {item}</p>)}</div></div><Link className="detail-primary" href="/get-started">Get started</Link></div></section>
    <section className="power-section"><div className="power-heading"><p className="detail-kicker">Treatment at a glance</p><h2>{product.featureTitle}</h2></div><div className="power-grid">{product.features.map((feature,index) => <article key={feature.title}><span>0{index+1}</span><div className="power-image"><img src={["/rejuvonix-member-phone.png","/rejuvonix-clinician.png","/rejuvonix-movement.png"][index]} alt="Rejuvonix care and healthy lifestyle" /></div><h3>{feature.title}</h3><p>{feature.copy}</p></article>)}</div></section>
    <section className="detail-how"><div><p className="detail-kicker">How it works</p><h2>From assessment to follow-up.</h2><p>Rejuvonix keeps each step clear while independent providers and pharmacies handle clinical care and fulfillment.</p></div><ol><li><span>01</span><div><h3>Tell us about your health</h3><p>Complete a secure online assessment.</p></div></li><li><span>02</span><div><h3>Provider evaluation</h3><p>A licensed provider reviews your information and treatment options.</p></div></li><li><span>03</span><div><h3>Your treatment plan</h3><p>If prescribed, receive directions selected for your needs.</p></div></li><li><span>04</span><div><h3>Delivery and follow-up</h3><p>Track fulfillment and return for provider check-ins.</p></div></li></ol></section>
    <section className="membership-detail"><div><p className="detail-kicker">Complete support</p><h2>More than medication.</h2><p>Keep assessment details, provider messages, fulfillment updates, progress check-ins and lifestyle guidance together.</p><Link className="detail-primary dark" href="/support">Explore the program</Link></div><div className="membership-photo"><img src="/rejuvonix-doctor-silhouette.png" alt="A clinician speaking with a patient during a telehealth visit" /></div><div className="membership-list">{["Personalized treatment plan","Secure provider messaging","Order and fulfillment updates","Progress check-ins","Nutrition and movement guidance"].map(item => <p key={item}><span>✓</span>{item}</p>)}</div></section>
    <section className="compare-detail"><div className="compare-heading"><p className="detail-kicker">Compare options</p><h2>Which treatment may be right for you?</h2><p>A licensed provider reviews your intake and determines what is medically appropriate.</p></div><div className="compare-grid">{related.map(item => <article key={item.slug}><div><img src={item.image} alt={`${item.name} packaging`} /></div><p>{item.status}</p><h3>{item.name}</h3><dl><dt>Format</dt><dd>{item.format}</dd><dt>Schedule</dt><dd>{item.cadence}</dd><dt>Ingredient</dt><dd>{item.ingredient}</dd></dl><Link href={`/treatments/${item.slug}`}>View details →</Link></article>)}</div><Link className="detail-secondary" href="/treatments">View all treatments</Link></section>
    <section className="future-banner"><img src="/rejuvonix-couple-walk.png" alt="Two adults walking together outdoors" /><div><p className="detail-kicker">Care for the long term</p><h2>Build a plan you can understand and follow.</h2><Link className="detail-primary" href="/get-started">Check eligibility</Link></div></section>
    <section className="safety-detail" id="important-safety"><div><p className="detail-kicker">Important safety information</p><h2>Know the risks before treatment.</h2></div><div><p>{product.safety}</p><p>Tell your provider about all medical conditions, allergies, pregnancy plans, and every prescription, over-the-counter medicine and supplement you use. Seek urgent care for a medical emergency.</p><Link href="/safety">Read the safety overview →</Link></div></section>
    <section className="detail-faq"><div><p className="detail-kicker">Frequently asked questions</p><h2>Common questions about {product.shortName}.</h2></div><div>{[[`Is ${product.shortName} guaranteed after the assessment?`,"No. A licensed provider decides whether treatment is appropriate."],["How is my dose selected?","Your provider selects the prescription and adjusts it only when clinically appropriate."],["Where does medication come from?","If prescribed, an independent licensed pharmacy dispenses and ships the medication."],["Can I ask questions after starting?","Yes. Use the platform for provider messages and required follow-up." ]].map(([question,answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="detail-closing"><p className="detail-kicker">Get started</p><h2>Find out which option may fit your health needs.</h2><Link className="detail-primary" href="/get-started">Start the assessment</Link><small>A prescription is not guaranteed.</small></section>
    <SiteFooter />
  </main>;
}
