"use client";

import { useState } from "react";
import Link from "next/link";

export function SiteHeader() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <><div className="detail-announcement">Online access to provider-led prescription weight care</div><header className="detail-header"><Link className="brand" href="/" onClick={() => setMenuOpen(false)}><img src="/rejuvonix-logo-mark.png" alt="" />REJUVONIX<span>.</span></Link><nav className={menuOpen ? "open" : ""} aria-label="Primary navigation"><Link href="/treatments" onClick={() => setMenuOpen(false)}>Treatments</Link><Link href="/compounded" onClick={() => setMenuOpen(false)}>Compounded</Link><Link href="/how-it-works" onClick={() => setMenuOpen(false)}>How it works</Link><Link href="/support" onClick={() => setMenuOpen(false)}>Support</Link></nav><div><Link className="detail-signin" href="/sign-in">Sign in</Link><Link className="detail-start" href="/get-started">Get started</Link></div><button className="detail-menu-button" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle navigation">Menu</button></header></>;
}

export function SiteFooter() {
  return <footer className="detail-footer"><div className="detail-footer-grid"><div><Link className="brand" href="/"><img src="/rejuvonix-logo-mark.png" alt="" />REJUVONIX<span>.</span></Link><p>Online access to prescription weight care.</p></div><div><strong>Explore</strong><Link href="/treatments">Treatments</Link><Link href="/compounded">Compounded care</Link><Link href="/how-it-works">How it works</Link></div><div><strong>Support</strong><Link href="/support">The program</Link><Link href="/faq">FAQs</Link><Link href="/safety">Safety</Link></div><div><strong>Account</strong><Link href="/sign-in">Sign in</Link><Link href="/get-started">Get started</Link><Link href="/support#contact">Contact</Link></div></div><div className="detail-disclaimer"><strong>Medical and platform disclaimer</strong><p>Rejuvonix is a technology and administrative-services platform, not a healthcare provider or pharmacy. Independent licensed healthcare professionals make all clinical decisions. If prescribed, medication is dispensed by an independent licensed pharmacy. Compounded medications are not FDA approved. Individual results vary.</p></div><div className="detail-footer-bottom"><span>© 2026 Rejuvonix. All rights reserved.</span><span>Wegovy® is a registered trademark of Novo Nordisk A/S. Zepbound® is a registered trademark of Eli Lilly and Company. Rejuvonix is not affiliated with or endorsed by these companies.</span></div></footer>;
}
