import Link from "next/link";
import { approvedGoalGroups } from "./service-data";
import { protocolGoals } from "./protocol-data";

function ProtocolMenuColumn(){return <span className="mega-column mega-protocols"><Link className="mega-title" href="/protocols">Protocols</Link><Link href="/protocols">All Protocols</Link>{protocolGoals.map((goal)=><Link href={`/protocols/${goal.slug}`} key={goal.slug}>{goal.name}</Link>)}</span>}

export function GoalMegaMenu(){return <span className="nav-dropdown mega-menu"><ProtocolMenuColumn/>{approvedGoalGroups.map((group)=><span className="mega-column" key={group.slug}><Link className="mega-title" href={`/goals/${group.slug}`}>{group.name}</Link>{group.services.slice(0, 5).map((service)=><Link href={group.slug === "weight-loss" ? `/treatments/${service.slug}` : `/services/${service.slug}`} key={service.slug}>{service.name}</Link>)}</span>)}<span className="mega-column mega-existing"><b>Rejuvonix care</b><Link href="/treatments">All treatments</Link><Link href="/compounded">Compounded care</Link><Link href="/how-it-works">How it works</Link><Link href="/support">Support</Link></span></span>}

export function SiteHeader(){return <><div className="detail-announcement">Online access to provider guided wellness programs</div><header className="detail-header program-detail-header"><Link className="brand" href="/"><img src="/rejuvonix-logo-mark.png" alt=""/>REJUVONIX<span>.</span></Link><nav aria-label="Primary navigation"><span className="nav-menu-group goals-menu"><Link href="/goals/weight-loss">Your Goals</Link><GoalMegaMenu/></span><span className="nav-menu-group membership-menu"><Link href="/membership">Membership</Link><span className="nav-dropdown"><Link href="/membership">Why Membership</Link><Link href="/how-it-works">How membership works</Link></span></span><span className="nav-menu-group resource-menu"><Link href="/support">Resource Center</Link><span className="nav-dropdown"><Link href="/how-it-works">How it works</Link><Link href="/support">Support</Link><Link href="/faq">FAQs</Link><Link href="/safety">Safety</Link></span></span><span className="nav-menu-group about-menu"><Link href="/how-it-works">About Us</Link><span className="nav-dropdown"><Link href="/how-it-works">Our approach</Link><Link href="/support">Our care model</Link><Link href="/safety">Clinical standards</Link></span></span></nav><div><Link className="detail-start account-only" href="/sign-in">Account</Link></div><details className="detail-mobile-menu"><summary>Menu</summary><div className="detail-mobile-panel"><Link href="/goals/weight-loss">Your Goals</Link><div className="detail-mobile-protocols"><b>Protocols</b><Link href="/protocols">All Protocols</Link>{protocolGoals.map((goal)=><Link href={`/protocols/${goal.slug}`} key={goal.slug}>{goal.name}</Link>)}</div><Link href="/treatments">Treatments</Link><Link href="/compounded">Compounded care</Link><Link href="/membership">Membership</Link><Link href="/support">Resource Center</Link><Link href="/how-it-works">About Us</Link><Link href="/sign-in">Account</Link></div></details></header></>}

function TrustMarks(){return <><div className="protocol-footer-trust" aria-label="Trust and fulfillment information"><div className="protocol-trust-mark"><img src="/hipaa-crest.png" alt="HIPAA compliant crest"/><span><strong>HIPAA Compliant*</strong></span></div><div className="protocol-trust-mark"><img src="/compounded-usa-crest.png" alt="Compounded in USA crest"/><span><strong>Compounded in USA*</strong></span></div><p className="protocol-trust-qualifier">*HIPAA statement applies to covered clinical workflows and participating entities. “Compounded in USA” applies only to eligible compounded medications prescribed when clinically appropriate and fulfilled by participating U.S. pharmacies.</p></div></>}

export function SiteFooter(){return <footer className="detail-footer"><div className="detail-footer-grid"><div><Link className="brand footer-brand" href="/"><img src="/rejuvonix-logo-mark.png" alt=""/>REJUVONIX<span>.</span></Link><p>Provider guided wellness pathways online.</p><a className="footer-email" href="mailto:info@rejuvonix.com">info@rejuvonix.com</a><TrustMarks/><div className="legitscript-reserved" aria-label="LegitScript certification seal placement pending verification"><span>Verification seal</span><small>Official LegitScript seal code required</small></div></div><div><strong>Explore</strong><Link href="/protocols">Protocols</Link><Link href="/treatments">Treatments</Link><Link href="/compounded">Compounded care</Link><Link href="/how-it-works">How it works</Link><Link href="/membership">Membership</Link></div><div><strong>Policies</strong><Link href="/terms">Terms and conditions</Link><Link href="/privacy">Privacy policy</Link><Link href="/privacy-practices">Privacy practices</Link><Link href="/refund-policy">Cancellation and refunds</Link><Link href="/telehealth-consent">Telehealth and medical consent</Link><Link href="/california-privacy">California privacy notice</Link><Link href="/patient-rights">Patient bill of rights</Link></div><div><strong>Support</strong><Link href="/support">Support</Link><Link href="/faq">FAQs</Link><Link href="/safety">Safety</Link><Link href="/accessibility">Accessibility</Link><Link href="/disclaimer">Medical disclaimer</Link></div></div><div className="detail-disclaimer"><strong>Medical and platform disclaimer</strong><p>Rejuvonix is a technology and administrative services platform, not a healthcare provider or pharmacy. Independent licensed healthcare professionals make all clinical decisions. If prescribed, medication is dispensed by an independent licensed pharmacy. Compounded medications are not FDA approved. Individual results vary.</p></div><div className="detail-footer-bottom"><span>© 2026 Rejuvonix. All rights reserved.</span><span>Wegovy® is a registered trademark of Novo Nordisk A/S. Rejuvonix is not affiliated with or endorsed by these companies.</span></div></footer>}
