"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { SiteFooter, SiteHeader } from "./SiteChrome";
import { CareJourney } from "./CareJourney";

const sections = ["Overview","Benefits","Care","Safety"];

export function WegovyInjectionExperience(){
  const [active,setActive]=useState(0);
  const railRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const ids=["wegovy-overview","wegovy-benefits","wegovy-care","wegovy-safety"];const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){const index=ids.indexOf(entry.target.id);if(index>=0)setActive(index)}})},{rootMargin:"-35% 0px -55%",threshold:0});ids.forEach(id=>{const el=document.getElementById(id);if(el)observer.observe(el)});return()=>observer.disconnect()},[]);
  const scrollCards=(direction:number)=>railRef.current?.scrollBy({left:direction*390,behavior:"smooth"});
  return <main className="wegovy-dynamic">
    <SiteHeader/>
    <aside className="wegovy-progress" aria-label="Page sections">{sections.map((item,index)=><a key={item} className={active===index?"active":""} href={`#wegovy-${item.toLowerCase()}`}><span></span>{item}</a>)}</aside>
    <section className="wegovy-hero" id="wegovy-overview"><div className="wegovy-hero-copy"><p className="dynamic-kicker">FDA-approved branded medication</p><h1>Wegovy®<br/>Injection</h1><p className="dynamic-lead">A once-weekly prescription GLP-1 medication with semaglutide.</p><div className="hero-facts"><div><b>Once weekly</b><span>Simple prescribed routine</span></div><div><b>Provider reviewed</b><span>Independent clinical care</span></div></div><Link className="dynamic-primary" href="/eligibility">Check eligibility <span>→</span></Link><a className="dynamic-safety" href="#wegovy-safety">Important safety information</a></div><div className="wegovy-product-stage"><div className="product-orbit orbit-one"></div><div className="product-orbit orbit-two"></div><p className="product-stage-note">Once-weekly care, designed around real life.</p><img src="/wegovy-pen-trio.png" alt="Three Wegovy injection pens"/><div className="float-fact fact-one"><small>FORMAT</small><strong>Injection</strong></div><div className="float-fact fact-two"><small>ROUTINE</small><strong>Once weekly</strong></div></div></section>
    <section className="wegovy-meet"><img src="/wegovy-member-outdoors.jpg" alt="Confident woman enjoying time outdoors"/><div className="meet-panel"><p className="dynamic-kicker">Meet</p><h2>Wegovy®<br/>Injection</h2><p>Wegovy® is an FDA-approved prescription medication used with reduced-calorie nutrition and increased physical activity for chronic weight management in eligible adults.</p><span>Continue to explore ↓</span></div></section>
    <section className="wegovy-explore" id="wegovy-benefits"><div className="explore-intro"><p className="dynamic-kicker">Why patients explore it</p><h2>One treatment.<br/>Different needs.</h2><div className="rail-controls"><button onClick={()=>scrollCards(-1)} aria-label="Previous benefits">←</button><button onClick={()=>scrollCards(1)} aria-label="Next benefits">→</button></div></div><div className="explore-rail" ref={railRef}>{[["01","Once-weekly routine","A prescribed schedule designed to fit into everyday life.","/wegovy-member-platform.jpg","Member reviewing care updates on her phone"],["02","Provider-led dosing","Your provider selects the prescription and manages any dose changes.","/wegovy-provider-review.jpg","Clinician speaking with a patient remotely"],["03","Support between check-ins","Follow messages, fulfillment updates and next steps through the platform.","/wegovy-followup-member.jpg","Member reviewing a care message at home"],["04","Built for real life","Treatment works alongside nutrition, movement and ongoing care.","/wegovy-movement-member.jpg","Woman holding a yoga mat after movement"]].map(([number,title,copy,image,alt])=><article key={number}><img src={image} alt={alt}/><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="care-moves" id="wegovy-care"><div className="moves-heading"><p className="dynamic-kicker">How care moves</p><h2>From your first questions to ongoing follow-up.</h2></div><div className="moves-path"><svg viewBox="0 0 1000 130" preserveAspectRatio="none" aria-hidden="true"><path d="M0 74 C120 5 220 120 350 56 S570 10 680 76 S870 130 1000 50"/></svg>{[["01","You connect","Complete the approved clinical assessment when available."],["02","Provider review","A licensed provider evaluates your information."],["03","Pharmacy coordination","If prescribed, a licensed pharmacy prepares fulfillment."],["04","You follow progress","Track next steps, messages and check-ins."]].map(([n,t,c],i)=><article key={n} style={{left:`${i*31}%`}}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>
    <section className="sticky-story"><div className="sticky-product"><img src="/wegovy-pen-trio.png" alt="Wegovy injection pens"/></div><div className="story-cards">{[["01","What it is","A prescription GLP-1 medication for chronic weight management in eligible adults."],["02","How it works","Semaglutide is a GLP-1 receptor agonist that can affect appetite and gastric emptying."],["03","How it is taken","Use once weekly exactly as prescribed and follow the device instructions."]].map(([n,t,c])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{c}</p></div><b>+</b></article>)}</div></section>
    <section className="real-life-banner"><img src="/wegovy-family-kitchen.jpg" alt="Family preparing a meal together at home"/><div><p className="dynamic-kicker">Everyday care</p><h2>Treatment that fits real life.</h2><p>Your provider-led plan can sit alongside nutrition, movement and routines that make sense for you.</p><Link className="dynamic-primary" href="/eligibility">Review my options <span>→</span></Link></div></section>
    <section className="provider-path"><div><p className="dynamic-kicker">Dose progression</p><h2>Your provider guides every step.</h2><p>Starting strength, timing and any adjustment are based on clinical judgment and tolerability.</p></div><div className="dose-track"><div className="track-line"><span style={{width:"58%"}}></span><i></i></div>{[["01","Start low","Begin only with the dose prescribed."],["02","Build gradually","Your provider reviews response and tolerability."],["03","Review progress","Discuss effects, questions and next steps."],["04","Maintain appropriately","Continue only as directed by your provider."]].map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>
    <section className="organized-care"><div><p className="dynamic-kicker">Connected support</p><h2>Care organized around you.</h2><ul><li>Provider messaging when integration is active</li><li>Fulfillment and delivery updates</li><li>Progress check-ins</li><li>Practical lifestyle guidance</li></ul></div><div className="telehealth-stack"><img src="/wegovy-telehealth-visit.jpg" alt="Doctor appearing on a tablet during a telehealth visit"/><div className="message-card"><small>CARE TEAM</small><strong>Provider message preview</strong></div><div className="checkin-card"><small>NEXT CHECK-IN</small><strong>Review your progress</strong></div></div></section>
    <section className="dynamic-compare"><div><p className="dynamic-kicker">Treatment options</p><h2>Compare formats with your provider.</h2></div><div className="compare-stage"><article className="side"><img src="/wegovy-pill.png" alt="Wegovy pill packaging"/><span>Daily pill</span></article><article className="center"><b>Current option</b><img src="/wegovy-pen-trio.png" alt="Wegovy injection pens"/><h3>Wegovy® Injection</h3><span>Once weekly</span></article><article className="side"><img src="/zepbound-injection.png" alt="Zepbound injection packaging"/><span>Weekly injection</span></article></div><div className="compare-dots"><span></span><span className="active"></span><span></span></div><Link href="/treatments">View all treatments →</Link></section>
    <section className="dynamic-safety-section" id="wegovy-safety"><div><p className="dynamic-kicker">Important safety information</p><h2>Understand the risks before treatment.</h2><p>Wegovy® has a boxed warning about the risk of thyroid C-cell tumors. Review your complete health history and the full prescribing information with your provider.</p><a href="https://www.wegovy.com/prescribing-information.html" rel="noreferrer">View prescribing information →</a></div><div>{[["Who should not use Wegovy®?","Do not use it if you or a family member have had medullary thyroid carcinoma or if you have MEN 2."],["What should I tell my provider?","Share all medical conditions, allergies, pregnancy plans and every medication or supplement you use."],["What side effects can occur?","Common effects can include nausea, vomiting, diarrhea, constipation and abdominal discomfort."],["What if I have urgent symptoms?","Seek immediate medical care for a severe allergic reaction, severe abdominal pain or another emergency."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="dynamic-closing"><div className="dna-ribbon">⌁</div><div><p className="dynamic-kicker">Your next step</p><h2>Ready to learn what may fit?</h2><Link className="dynamic-primary" href="/eligibility">Check eligibility <span>→</span></Link><small>A prescription is not guaranteed.</small></div></section>
    <section className="journey-page" id="wegovy-journey"><div className="journey-page-heading"><p className="dynamic-kicker">The nine-stage journey</p><h2>From program selection to reassessment.</h2><p><a href="https://www.accessdata.fda.gov/drugsatfda_docs/label/2026/215256s033lbl.pdf" target="_blank" rel="noreferrer">Official FDA Prescribing Information (PDF) ↗</a></p></div><CareJourney/></section>
    <SiteFooter/>
  </main>
}
