import Link from "next/link";
import { SiteFooter, SiteHeader } from "./SiteChrome";
import { CareJourney } from "./CareJourney";

const benefits=[
  ["01","Once-daily pill","An oral GLP-1 routine with no injection device.","/pill-benefit-daily.png","A tablet, water and a refined daily-routine motif"],
  ["02","FDA approved","A branded semaglutide medication for chronic weight management in eligible patients.","/pill-benefit-approved.png","A clinical approval shield and document motif"],
  ["03","Provider guided","An independent licensed provider reviews eligibility, contraindications and follow-up needs.","/pill-benefit-provider.png","A licensed provider guiding care by telehealth"],
];

export function WegovyPillExperience(){return <main className="pill-page">
  <SiteHeader/>
  <section className="pill-hero">
    <div className="pill-hero-copy"><p className="pill-kicker">The first FDA-approved oral GLP-1 for weight management</p><h1>Weight care.<br/><em>Now in a pill.</em></h1><p className="pill-lead">Wegovy® Pill is once-daily prescription semaglutide for eligible adults—paired with provider-led care, progress check-ins and lifestyle support.</p><div className="pill-actions"><Link className="pill-primary" href="/eligibility">Check eligibility <span>→</span></Link><a href="#pill-safety">Important safety information</a></div></div>
    <div className="pill-hero-stage"><div className="pill-halo"></div><div className="pill-type" aria-hidden="true">ONCE DAILY</div><img src="/novo-pills-clean.png" alt="Three Wegovy tablets arranged on a Rejuvonix aqua background"/><span className="pill-float float-top">NO INJECTION</span><span className="pill-float float-bottom">SEMAGLUTIDE</span></div>
  </section>
  <section className="pill-marquee" aria-label="Wegovy Pill highlights"><span>Once daily</span><i>•</i><span>Needle free</span><i>•</i><span>Provider reviewed</span><i>•</i><span>FDA approved</span></section>
  <section className="pill-intro"><div><p className="pill-kicker">Meet Wegovy® Pill</p><h2>A familiar ingredient. A new daily format.</h2></div><div><p>Wegovy® Pill contains semaglutide, a GLP-1 receptor agonist. It is used with reduced-calorie nutrition and increased physical activity for chronic weight management in eligible patients.</p><Link href="/eligibility">Start the online assessment →</Link></div></section>
  <section className="pill-benefits">{benefits.map(([number,title,copy,image,alt])=><article key={number}><span>{number}</span><div className="pill-benefit-orb"><img src={image} alt={alt}/></div><h3>{title}</h3><p>{copy}</p></article>)}</section>
  <section className="pill-life"><img src="/wegovy-pill-support-unique.png" alt="A member reviewing her care plan from home"/><div className="pill-life-card"><p className="pill-kicker">Designed for real routines</p><h2>Care that lives where you do.</h2><p>Your plan can bring medication guidance, nutrition support, movement education and provider follow-up into one connected online experience.</p><ul><li>Online assessment pathway</li><li>Independent provider review</li><li>Progress and tolerance check-ins</li><li>Order and fulfillment updates</li></ul></div></section>
  <section className="pill-process"><div className="pill-process-heading"><p className="pill-kicker">How Rejuvonix works</p><h2>Four clear steps. One connected plan.</h2></div><ol><li><span>01</span><h3>Tell us about your health</h3><p>Complete the approved clinical assessment when it becomes available.</p></li><li><span>02</span><h3>Meet your provider</h3><p>An independent licensed provider reviews your information.</p></li><li><span>03</span><h3>Receive your plan</h3><p>If appropriate, your provider selects treatment and directions.</p></li><li><span>04</span><h3>Stay connected</h3><p>Return for check-ins, questions and next steps.</p></li></ol></section>
  <section className="pill-support"><div className="pill-support-art"><img src="/wegovy-pill-support-unique.png" alt="A member using the Rejuvonix platform at home"/><span>YOUR CARE<br/>IN ONE PLACE</span></div><div><p className="pill-kicker">Beyond the prescription</p><h2>Support makes the plan sustainable.</h2><p>Medication is one part of a larger care experience. Rejuvonix keeps your assessment, provider communication and progress rhythm together.</p><div className="pill-support-grid"><p><b>01</b>Provider messaging</p><p><b>02</b>Nutrition guidance</p><p><b>03</b>Movement support</p><p><b>04</b>Progress check-ins</p></div></div></section>
  <section className="pill-safety" id="pill-safety"><div><p className="pill-kicker">Important safety information</p><h2>Understand the risks before treatment.</h2></div><div><p><strong>WARNING: RISK OF THYROID C-CELL TUMORS.</strong> Wegovy® has a boxed warning. Do not use Wegovy® if you or a family member have had medullary thyroid carcinoma or if you have Multiple Endocrine Neoplasia syndrome type 2.</p><p>Tell your provider about all medical conditions, allergies, pregnancy plans, and every medicine or supplement you take. Review the complete prescribing information supplied with the medication.</p><Link href="/safety">Read the full safety overview →</Link></div></section>
  <section className="pill-closing"><div className="pill-closing-ring" aria-hidden="true"></div><img src="/novo-pills-clean.png" alt="Wegovy tablets"/><div><p className="pill-kicker">Your next step</p><h2>See whether Wegovy® Pill may fit your care plan.</h2><Link className="pill-primary" href="/eligibility">Start the assessment <span>→</span></Link><small>A prescription is not guaranteed.</small></div></section>
  <section className="journey-page" id="pill-journey"><div className="journey-page-heading"><p className="pill-kicker">The nine-stage journey</p><h2>From program selection to reassessment.</h2><p><a href="https://www.accessdata.fda.gov/drugsatfda_docs/label/2026/215256s033lbl.pdf" target="_blank" rel="noreferrer">Official FDA Prescribing Information (PDF) ↗</a></p></div><CareJourney/></section>
  <SiteFooter/>
</main>}
