"use client";
import {useState} from "react";

const conditions=["None of these","Medullary thyroid cancer","Family history of medullary thyroid cancer","MEN 2","Pancreatitis","Active gallbladder disease","Type 1 diabetes","Insulin-dependent Type 2 diabetes","Kidney disease","Liver disease","Active cancer","Eating disorder","Active drug or alcohol misuse","Bipolar disorder","Schizophrenia","Persistent glucose below 60 mg/dL"];
const allergyOptions=["None known","Glycine","Vitamin B12","Vitamin B3","Not sure"];

export default function WeightLossClinicalDraft({onComplete}:{onComplete:()=>void}){
  const[screen,setScreen]=useState(0);
  const[sex,setSex]=useState("");
  const[pregnancy,setPregnancy]=useState("");
  const[selectedConditions,setSelectedConditions]=useState<string[]>([]);
  const[surgery,setSurgery]=useState("");
  const[surgeryDetails,setSurgeryDetails]=useState("");
  const[priorGlp1,setPriorGlp1]=useState("");
  const[glpDetails,setGlpDetails]=useState({name:"",dose:"",lastDate:"",duration:"",sideEffects:""});
  const[currentMeds,setCurrentMeds]=useState("");
  const[medDetails,setMedDetails]=useState("");
  const[allergies,setAllergies]=useState<string[]>([]);
  const[otherAllergies,setOtherAllergies]=useState("");
  const toggle=(value:string,current:string[],setter:(next:string[])=>void,noneLabel:string)=>{
    if(value===noneLabel){setter(current.includes(value)?[]:[value]);return;}
    setter(current.includes(value)?current.filter(item=>item!==value):[...current.filter(item=>item!==noneLabel),value]);
  };
  const next=()=>setScreen(value=>Math.min(5,value+1));
  const back=()=>setScreen(value=>Math.max(0,value-1));
  return <div className="clinical-draft">
    <div className="clinical-preview-note"><strong>Clinical configuration preview</strong><span>Answers remain on this screen only and are not submitted or saved.</span></div>
    {screen>0&&<button type="button" className="clinical-back" onClick={back}>← Previous clinical section</button>}
    {screen===0&&<section><p className="eligibility-kicker">Medical context · Draft 1 of 6</p><h2>Help the provider understand your starting point.</h2><fieldset><legend>What sex were you assigned at birth?</legend><div className="clinical-choice-row">{["Male","Female","Prefer not to say"].map(value=><button className={sex===value?"selected":""} onClick={()=>setSex(value)} key={value}>{value}</button>)}</div></fieldset>{sex==="Female"&&<fieldset><legend>Are you pregnant, breastfeeding, or trying to conceive?</legend><div className="clinical-choice-row">{["No","Yes","Not sure"].map(value=><button className={pregnancy===value?"selected":""} onClick={()=>setPregnancy(value)} key={value}>{value}</button>)}</div><small>This answer is flagged for provider review; this preview does not determine eligibility.</small></fieldset>}<button className="eligibility-continue" disabled={!sex||(sex==="Female"&&!pregnancy)} onClick={next}>Continue <span>→</span></button></section>}
    {screen===1&&<section><p className="eligibility-kicker">Health history · Draft 2 of 6</p><h2>Have you been diagnosed with any of these conditions?</h2><p className="clinical-help">Select every answer that applies. No selection creates an automatic approval or denial.</p><div className="clinical-check-grid">{conditions.map(value=><button className={selectedConditions.includes(value)?"selected":""} onClick={()=>toggle(value,selectedConditions,setSelectedConditions,"None of these")} key={value}><span>{selectedConditions.includes(value)?"✓":""}</span>{value}</button>)}</div><button className="eligibility-continue" disabled={!selectedConditions.length} onClick={next}>Continue <span>→</span></button></section>}
    {screen===2&&<section><p className="eligibility-kicker">Procedures · Draft 3 of 6</p><h2>Have you had surgeries or procedures relevant to your care?</h2><div className="clinical-choice-row">{["No","Yes"].map(value=><button className={surgery===value?"selected":""} onClick={()=>setSurgery(value)} key={value}>{value}</button>)}</div>{surgery==="Yes"&&<label className="clinical-text-label">Procedure and year<textarea value={surgeryDetails} onChange={event=>setSurgeryDetails(event.target.value)} placeholder="Example: procedure name, 2024"/></label>}<label className="clinical-text-label">Weight-loss surgery history<select defaultValue=""><option value="" disabled>Select one</option><option>None</option><option>Gastric bypass</option><option>Duodenal switch</option><option>Lap band</option><option>Gastric sleeve</option><option>Not sure</option></select></label><button className="eligibility-continue" disabled={!surgery||(surgery==="Yes"&&!surgeryDetails.trim())} onClick={next}>Continue <span>→</span></button></section>}
    {screen===3&&<section><p className="eligibility-kicker">Medication history · Draft 4 of 6</p><h2>Have you used a GLP-1 medication?</h2><div className="clinical-choice-row">{["Never taken","Previously or currently taking"].map(value=><button className={priorGlp1===value?"selected":""} onClick={()=>setPriorGlp1(value)} key={value}>{value}</button>)}</div>{priorGlp1==="Previously or currently taking"&&<div className="clinical-field-grid"><label>Medication name<input value={glpDetails.name} onChange={event=>setGlpDetails({...glpDetails,name:event.target.value})}/></label><label>Most recent dose<input value={glpDetails.dose} onChange={event=>setGlpDetails({...glpDetails,dose:event.target.value})}/></label><label>Most recent dose date<input type="date" value={glpDetails.lastDate} onChange={event=>setGlpDetails({...glpDetails,lastDate:event.target.value})}/></label><label>How long used<input value={glpDetails.duration} onChange={event=>setGlpDetails({...glpDetails,duration:event.target.value})}/></label><label className="wide">Side effects, if any<textarea value={glpDetails.sideEffects} onChange={event=>setGlpDetails({...glpDetails,sideEffects:event.target.value})}/></label></div>}<button className="eligibility-continue" disabled={!priorGlp1||(priorGlp1!=="Never taken"&&(!glpDetails.name||!glpDetails.dose||!glpDetails.lastDate||!glpDetails.duration))} onClick={next}>Continue <span>→</span></button></section>}
    {screen===4&&<section><p className="eligibility-kicker">Medications and allergies · Draft 5 of 6</p><h2>What else should the provider review?</h2><fieldset><legend>Do you take medications or supplements?</legend><div className="clinical-choice-row">{["No","Yes"].map(value=><button className={currentMeds===value?"selected":""} onClick={()=>setCurrentMeds(value)} key={value}>{value}</button>)}</div></fieldset>{currentMeds==="Yes"&&<label className="clinical-text-label">Names and doses<textarea value={medDetails} onChange={event=>setMedDetails(event.target.value)}/></label>}<fieldset><legend>Known ingredient allergies</legend><div className="clinical-check-grid compact">{allergyOptions.map(value=><button className={allergies.includes(value)?"selected":""} onClick={()=>toggle(value,allergies,setAllergies,"None known")} key={value}><span>{allergies.includes(value)?"✓":""}</span>{value}</button>)}</div></fieldset><label className="clinical-text-label">Other medication or food allergies<textarea value={otherAllergies} onChange={event=>setOtherAllergies(event.target.value)} placeholder="Enter details, or leave blank if none"/></label><button className="eligibility-continue" disabled={!currentMeds||(currentMeds==="Yes"&&!medDetails.trim())||!allergies.length} onClick={next}>Continue <span>→</span></button></section>}
    {screen===5&&<section className="clinical-review"><p className="eligibility-kicker">Provider-review draft · 6 of 6</p><h2>The clinical question set is ready for formal review.</h2><ul><li>Nothing entered here has been saved or transmitted.</li><li>No answer has approved or disqualified you.</li><li>Identity, contact, address, consent, uploads and submission stay disabled until EmberFlow’s official sandbox and approved policies are connected.</li></ul><button className="eligibility-continue" onClick={onComplete}>Continue to handoff preview <span>→</span></button></section>}
  </div>;
}
