import Link from "next/link";
import {notFound} from "next/navigation";
import {SiteFooter,SiteHeader} from "../../components/SiteChrome";
import {findProtocol,findProtocolGoal,protocolGoals,protocols,protocolsForGoal} from "../../components/protocol-data";

export function generateStaticParams(){return [...protocolGoals.map(({slug})=>({slug})),...protocols.map(({slug})=>({slug}))];}

export default async function ProtocolRoute({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const goal=findProtocolGoal(slug);
  if(goal){
    const items=protocolsForGoal(goal.slug);
    return <main className="detail-page protocols-page"><SiteHeader/>
      <section className="protocol-category-hero"><div><p className="detail-kicker">Protocols · {goal.name}</p><h1>{goal.name} protocols.</h1><p>{goal.intro}</p><Link className="detail-primary" href={goal.assessmentRoute}>Start {goal.name.toLowerCase()} assessment</Link></div><div className="protocol-category-count"><strong>{String(items.length).padStart(2,"0")}</strong><span>catalog entries</span></div></section>
      <nav className="protocol-filter-bar" aria-label="Protocol categories"><Link href="/protocols">All Protocols</Link>{protocolGoals.map((item)=><Link className={item.slug===goal.slug?"active":""} href={`/protocols/${item.slug}`} key={item.slug}>{item.name}</Link>)}</nav>
      <section className="protocol-library"><div className="protocol-library-heading"><div><p className="detail-kicker">Explore {goal.name}</p><h2>Review the available education before sharing health information.</h2></div><p>Category placement is for discovery. It does not establish an approved indication, guarantee availability, or replace an independent provider&apos;s clinical judgment.</p></div><div className="protocol-grid">{items.map((protocol,index)=><Link className="protocol-card" href={`/protocols/${protocol.slug}`} key={protocol.slug}><span className="protocol-card-number">{String(index+1).padStart(2,"0")}</span><span className="protocol-card-category">{protocol.sourceCategory}</span><h3>{protocol.name}</h3><p>{protocol.summary}</p><span className={`protocol-doc-status status-${protocol.documentation.status}`}>{protocol.documentation.status==="coa-verified"?"COA available":protocol.documentation.label}</span><b>Open protocol →</b></Link>)}</div></section>
      <SiteFooter/></main>;
  }

  const protocol=findProtocol(slug);
  if(!protocol) notFound();
  const primaryGoal=protocolGoals.find((goalItem)=>goalItem.slug===protocol.goals[0]);
  return <main className="detail-page protocol-detail-page"><SiteHeader/>
    <section className="protocol-detail-hero"><div><p className="detail-kicker">Protocol education · {protocol.sourceCategory}</p><h1>{protocol.name}</h1><p>{protocol.summary}</p><div className="protocol-detail-actions">{primaryGoal&&<Link className="detail-primary" href={primaryGoal.assessmentRoute}>Start {primaryGoal.name.toLowerCase()} assessment</Link>}<a href="#quality">Quality & documentation ↓</a></div></div><aside><span>RELATED GOALS</span>{protocol.goals.map((goalSlug)=><Link href={`/protocols/${goalSlug}`} key={goalSlug}>{protocolGoals.find((item)=>item.slug===goalSlug)?.name} →</Link>)}</aside></section>
    <section className="protocol-story-grid"><article><span>01</span><p className="detail-kicker">Understand</p><h2>What this entry means.</h2><p>This page provides structured education and a path to independent clinical review. Inclusion in the master protocol library is not a prescription, endorsement, guarantee of availability or statement that the protocol is appropriate for a particular person.</p></article><article><span>02</span><p className="detail-kicker">Discuss</p><h2>What a provider may need to review.</h2><ul>{protocol.discussionPoints.map((point)=><li key={point}>{point}</li>)}</ul></article><article><span>03</span><p className="detail-kicker">Verify</p><h2>Regulatory and clinical context.</h2><p>{protocol.regulatoryNote}</p></article></section>
    <section className="protocol-pipeline"><div><p className="detail-kicker">Connected pathway</p><h2>From discovery to documented next steps.</h2><p>Rejuvonix keeps the protocol pathway connected without bypassing provider review.</p></div><ol><li><span>01</span><strong>Learn</strong><p>Review the protocol education and its regulatory context.</p></li><li><span>02</span><strong>Assess</strong><p>Complete the appropriate Rejuvonix assessment when you are ready.</p></li><li><span>03</span><strong>Provider review</strong><p>An independent licensed provider determines whether any treatment is appropriate.</p></li><li><span>04</span><strong>Source & document</strong><p>If treatment is prescribed, pharmacy/source and applicable quality documentation remain connected to the pathway.</p></li></ol></section>
    <section className="protocol-quality" id="quality"><div><p className="detail-kicker">Quality & documentation</p><h2>Documentation follows the exact item.</h2><p>Rejuvonix only displays a COA after the exact item-to-document relationship has been verified. We do not infer, substitute or reuse another product&apos;s certificate.</p></div><div className="protocol-document-card"><span className={`protocol-doc-status status-${protocol.documentation.status}`}>{protocol.documentation.status==="coa-verified"?"COA verified":protocol.documentation.label}</span><h3>{protocol.name}</h3>{protocol.documentation.lot&&<p><b>Lot:</b> {protocol.documentation.lot}</p>}{protocol.documentation.testedAt&&<p><b>Test date:</b> {protocol.documentation.testedAt}</p>}{protocol.documentation.source&&<p><b>Source:</b> {protocol.documentation.source}</p>}{protocol.documentation.url?<a className="detail-primary" href={protocol.documentation.url} target="_blank" rel="noreferrer">View documentation ↗</a>:<p className="protocol-document-note">No COA link is displayed for this item until its exact source document is verified. Where a COA is not applicable, official prescribing or pharmacy documentation is used instead.</p>}</div></section>
    <section className="protocol-closing"><p className="detail-kicker">Next step</p><h2>Clinical decisions stay with licensed providers.</h2><p>Completing an assessment does not guarantee treatment or a prescription.</p>{primaryGoal&&<Link className="detail-primary" href={primaryGoal.assessmentRoute}>Continue to {primaryGoal.name.toLowerCase()} assessment</Link>}</section>
    <SiteFooter/>
  </main>;
}
