import Link from "next/link";
import {notFound} from "next/navigation";
import {SiteFooter,SiteHeader} from "../../components/SiteChrome";
import {ProtocolTrustStrip} from "../../components/ProtocolCard";
import {ProtocolShelf} from "../../components/ProtocolShelf";
import {findProtocol,findProtocolGoal,protocolGoals,protocols,protocolsForGoal} from "../../components/protocol-data";
import { intakeUrl } from "../../components/routing";
import {ProtocolGoalOrbit} from "../../components/ProtocolGoalOrbit";

export function generateStaticParams(){return [...protocolGoals.map(({slug})=>({slug})),...protocols.map(({slug})=>({slug}))];}

function DocumentationStatus({status,label}:{status:string;label:string}){
  return <span className={`protocol-doc-status status-${status}`}>{label}</span>;
}

export default async function ProtocolRoute({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const goal=findProtocolGoal(slug);
  if(goal){
    const items=protocolsForGoal(goal.slug);
    return <main className="detail-page protocols-page"><SiteHeader/>
      <section className="protocol-category-hero"><div><p className="detail-kicker">Protocols · {goal.name}</p><h1>{goal.name} protocols.</h1><p>{goal.intro}</p><Link className="detail-primary" href={goal.assessmentRoute}>Start {goal.name.toLowerCase()} assessment</Link></div><div className="protocol-category-count"><img src="/v6/compounded-medication-generic.png" alt="" aria-hidden="true"/><strong className="protocol-count-number">{items.length}</strong><span>CATALOG ENTRIES</span></div></section>
      <nav className="protocol-filter-bar" aria-label="Protocol categories"><Link href="/protocols">All Protocols</Link>{protocolGoals.map((item)=><Link className={item.slug===goal.slug?"active":""} href={`/protocols/${item.slug}`} key={item.slug}>{item.name}</Link>)}</nav>
      <ProtocolTrustStrip/>
      <section className="protocol-library"><div className="protocol-library-heading"><div><p className="detail-kicker">Explore {goal.name}</p><h2>Review the available education before sharing health information.</h2></div><p>Category placement is for discovery. It does not establish an approved indication, guarantee availability, or replace an independent provider&apos;s clinical judgment.</p></div><ProtocolShelf protocols={items}/></section>
      <SiteFooter/></main>;
  }

  const protocol=findProtocol(slug);
  if(!protocol) notFound();
  const primaryGoal=protocolGoals.find((goalItem)=>goalItem.slug===protocol.goals[0]);
  const batches=protocol.documentation.batches??[];
  return <main className="detail-page protocol-detail-page"><SiteHeader/>
    <section className="protocol-detail-hero protocol-detail-hero-v6"><div className="protocol-detail-copy"><p className="detail-kicker">Protocol education · {protocol.sourceCategory}</p><h1>{protocol.name}</h1><p>{protocol.summary}</p></div><div className="protocol-hero-product" aria-label={`${protocol.name} product visualization`}><div className="protocol-bottle-halo"></div><ProtocolGoalOrbit goals={protocol.goals.map((goalSlug)=>protocolGoals.find((item)=>item.slug===goalSlug)?.name??goalSlug)}/><img src={protocol.image} alt={protocol.imageAlt}/></div><div className="protocol-detail-lower"><div className="protocol-detail-actions">{primaryGoal&&<Link className="detail-primary" href={intakeUrl(protocol.intakeType)}>Start {primaryGoal.name.toLowerCase()} assessment</Link>}<a className="protocol-glow-link" href="#quality">Quality & documentation ↓</a></div><aside><span>RELATED GOALS</span><div>{protocol.goals.map((goalSlug)=><Link href={`/protocols/${goalSlug}`} key={goalSlug}>{protocolGoals.find((item)=>goalSlug===item.slug)?.name} →</Link>)}</div></aside></div></section>
    <section className="protocol-story-grid"><article><span>01</span><p className="detail-kicker">Understand</p><h2>What this entry means.</h2><p>This page provides structured education and a path to independent clinical review. Inclusion in the master protocol library is not a prescription, endorsement, guarantee of availability or statement that the protocol is appropriate for a particular person.</p></article><article><span>02</span><p className="detail-kicker">Discuss</p><h2>What a provider may need to review.</h2><ul>{protocol.discussionPoints.map((point)=><li key={point}>{point}</li>)}</ul></article><article><span>03</span><p className="detail-kicker">Verify</p><h2>Regulatory and clinical context.</h2><p>{protocol.regulatoryNote}</p></article></section>
    <section className="protocol-pipeline"><div><p className="detail-kicker">Connected pathway</p><h2>From discovery to documented next steps.</h2><p>Rejuvonix keeps the protocol pathway connected without bypassing provider review.</p></div><ol><li><span>01</span><strong>Learn</strong><p>Review the protocol education and its regulatory context.</p></li><li><span>02</span><strong>Assess</strong><p>Complete the appropriate Rejuvonix assessment when you are ready.</p></li><li><span>03</span><strong>Provider review</strong><p>An independent licensed provider determines whether any treatment is appropriate.</p></li><li><span>04</span><strong>Source & document</strong><p>If treatment is prescribed, pharmacy/source and applicable quality documentation remain connected to the pathway.</p></li></ol></section>
    <section className="protocol-quality" id="quality"><div><p className="detail-kicker">Quality & documentation</p><h2>Documentation follows the exact formulation and batch.</h2><p>COAs shown here are the supplied documents for the named formulation and lot. Original certificate files are preserved unchanged. FDA-approved finished products use official prescribing documentation; compounded formulations may also have their own batch-specific COAs.</p></div><div className="protocol-document-card"><DocumentationStatus status={protocol.documentation.status} label={protocol.documentation.status==="official-documentation"?protocol.documentation.label:batches.length?"COA available":protocol.documentation.label}/><h3>{protocol.name}</h3>{protocol.documentation.source&&<p><b>Primary documentation:</b> {protocol.documentation.source}</p>}{protocol.documentation.url&&<a className="detail-primary" href={protocol.documentation.url} target="_blank" rel="noreferrer">View official documentation ↗</a>}{protocol.documentation.status==="official-documentation"&&<p className="protocol-document-note">For the FDA-approved finished-product pathway, a COA is not required. Any compounded batch certificates shown below apply only to the specific compounded formulation and lot listed.</p>}{!protocol.documentation.url&&!batches.length&&<p className="protocol-document-note">Quality documentation is linked here when a specific formulation or batch document is supplied for this protocol.</p>}</div></section>
    {batches.length>0&&<section className="protocol-batches" aria-labelledby="batch-coa-title"><div className="protocol-section-heading"><p className="detail-kicker">Batch-by-batch COAs</p><h2 id="batch-coa-title">Review the certificate package for each listed batch.</h2><p>Some batches include more than one companion record. Part 1 and Part 2 links stay grouped under the same lot so the complete documentation set remains intact.</p></div><div className="protocol-batch-grid">{batches.map((batch,index)=><article className="protocol-batch-card" key={batch.id}><span className="protocol-batch-index">{String(index+1).padStart(2,"0")}</span><p className="protocol-batch-label">{batch.label}</p><h3>{batch.formulation}</h3><dl><div><dt>Lot / Batch</dt><dd>{batch.lot}</dd></div><div><dt>Laboratory</dt><dd>{batch.laboratory}</dd></div><div><dt>Document date</dt><dd>{batch.testedAt}</dd></div></dl><div className="protocol-batch-actions"><a className="detail-primary" href={batch.url} target="_blank" rel="noreferrer">View complete COA ↗</a>{batch.parts?.map((part)=><a className="protocol-part-link" href={part.url} target="_blank" rel="noreferrer" key={part.label}>{part.label} ↗</a>)}</div></article>)}</div></section>}
    <section className="protocol-closing"><p className="detail-kicker">Next step</p><h2>Clinical decisions stay with licensed providers.</h2><p>Completing an assessment does not guarantee treatment or a prescription.</p>{primaryGoal&&<Link className="detail-primary" href={intakeUrl(protocol.intakeType)}>Continue to {primaryGoal.name.toLowerCase()} assessment</Link>}</section>
    <SiteFooter/>
  </main>;
}
