"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {SiteFooter,SiteHeader} from "../components/SiteChrome";
const stages=[
{n:"01",title:"Personalized plan",copy:"Directions and next steps selected by your provider.",image:"/support-stage-plan.png"},
{n:"02",title:"Provider messaging",copy:"A planned channel for treatment-related questions and follow-up.",image:"/support-stage-message.png"},
{n:"03",title:"Fulfillment updates",copy:"Follow pharmacy and delivery progress when prescribed.",image:"/support-stage-fulfillment.png"},
{n:"04",title:"Progress check-ins",copy:"Record changes, tolerance and questions for provider review.",image:"/support-stage-progress.png"},
{n:"05",title:"Nutrition guidance",copy:"Practical ideas that support everyday choices.",image:"/support-stage-nutrition.png"},
{n:"06",title:"Movement guidance",copy:"Simple ways to build activity around your current routine.",image:"/support-stage-movement.png"},
];
export default function SupportPage(){const[active,setActive]=useState(0);const touch=useRef<number|null>(null);const choose=(next:number)=>setActive((next+stages.length)%stages.length);const stage=stages[active];useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const timer=window.setInterval(()=>setActive(current=>(current+1)%stages.length),5000);return()=>window.clearInterval(timer)},[active]);return <main className="detail-page support-detail-page"><SiteHeader/>
<section className="info-hero support-info"><div><p className="detail-kicker">The Rejuvonix program</p><h1>Your care, organized in one place.</h1><p>The current site previews assessment details, provider messages, fulfillment updates, progress check-ins and practical lifestyle support. Clinical functions remain disabled.</p><Link className="detail-primary" href="/eligibility">Explore the preview</Link></div><img src="/support-member-unique.png" alt="A member using the Rejuvonix health app at home"/></section>
<section className="support-experience-section"><div className="support-experience-heading"><p className="detail-kicker">Planned experience</p><h2>Support that continues after the assessment.</h2><p>Move through each part of the connected care experience.</p></div><div className="support-experience-stage" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(touch.current===null)return;const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>48)choose(active+(delta<0?1:-1));touch.current=null}}><div className="support-experience-image"><img key={stage.image} src={stage.image} alt=""/><span>{stage.n}</span></div><div className="support-experience-copy" aria-live="polite"><p className="detail-kicker">Stage {stage.n}</p><h3>{stage.title}</h3><p>{stage.copy}</p><div className="support-stage-controls"><button type="button" onClick={()=>choose(active-1)} aria-label="Previous stage">←</button><span>{active+1} / {stages.length}</span><button type="button" onClick={()=>choose(active+1)} aria-label="Next stage">→</button></div></div></div><div className="support-experience-tabs" role="tablist" aria-label="Care stages">{stages.map((item,index)=><button key={item.n} type="button" className={index===active?"active":""} onClick={()=>setActive(index)} role="tab" aria-selected={index===active}><span>{item.n}</span><strong>{item.title}</strong></button>)}</div></section>
<section className="support-routines"><img src="/support-routines-v2.png" alt="Two fit adults building a practical movement routine outdoors"/><div className="support-routines-glass"><p className="detail-kicker">Everyday support</p><h2>Small routines matter.</h2><p>Use realistic nutrition, movement and maintenance guidance alongside the treatment plan selected by your provider.</p></div></section>
<section className="contact-section" id="contact"><div><p className="detail-kicker">Contact support</p><h2>Need help with the website or next step?</h2></div><div><a href="mailto:info@rejuvonix.com">info@rejuvonix.com</a><p>Do not email medical information while the clinical platform is disconnected. For medical emergencies, call 911 or seek immediate in-person care.</p></div></section><SiteFooter/></main>}
